### ISSUE TITLE
Issue with https://github.com/chanzuckerberg/blessclient/pull/113 on new release binary but not on local build

### ISSUE THREAD

**Issue by vivianho** [chanzuckerberg/blessclient#115]
When I run `go run main.go run` on master branch, this is successful. However, when I run from the binary blessclient_0.4.3_darwin_amd64.tar.gz from the latest releases, it fails:

```
➜  blessclient git:(master) go run main.go run
➜  blessclient git:(master) rm ~/.ssh/blessid-cert.pub
➜  blessclient git:(master) blessclient2 run
ERRO[0000] Error in retrieving AWS Okta session credentials: Error retrieving credentials using aws-okta. Run `blessclient okta-setup` and then try again.: The specified item could not be found in the keyring..
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x19e2e36]

goroutine 1 [running]:
github.com/chanzuckerberg/blessclient/pkg/config.(*Config).GetAWSUsername(0xc0000aa5b0, 0x2026ca0, 0xc00038e240, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/elopez/workspace/go/src/github.com/chanzuckerberg/blessclient/pkg/config/config.go:235 +0x186
github.com/chanzuckerberg/blessclient/cmd.processRegion(0x2026ca0, 0xc00038e240, 0xc0000aa5b0, 0xc0003a8000, 0xc0000ae990, 0x9, 0xc0001264e0, 0x24, 0x0, 0x0)
	/home/elopez/workspace/go/src/github.com/chanzuckerberg/blessclient/cmd/run.go:111 +0x213
github.com/chanzuckerberg/blessclient/cmd.glob..func7(0x2b9b380, 0x2bbf048, 0x0, 0x0, 0x0, 0x0)
	/home/elopez/workspace/go/src/github.com/chanzuckerberg/blessclient/cmd/run.go:93 +0x955
github.com/chanzuckerberg/blessclient/vendor/github.com/spf13/cobra.(*Command).execute(0x2b9b380, 0x2bbf048, 0x0, 0x0, 0x2b9b380, 0x2bbf048)
	/home/elopez/workspace/go/src/github.com/chanzuckerberg/blessclient/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/chanzuckerberg/blessclient/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2b9baa0, 0x0, 0x0, 0x1aa2bd1)
	/home/elopez/workspace/go/src/github.com/chanzuckerberg/blessclient/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/chanzuckerberg/blessclient/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/elopez/workspace/go/src/github.com/chanzuckerberg/blessclient/vendor/github.com/spf13/cobra/command.go:800
github.com/chanzuckerberg/blessclient/cmd.Execute(...)
	/home/elopez/workspace/go/src/github.com/chanzuckerberg/blessclient/cmd/root.go:53
main.main()
	/home/elopez/workspace/go/src/github.com/chanzuckerberg/blessclient/main.go:9 +0x2f
```

**Comment by vivianho** [comment]
@edulop91 do you know if anything is done differently that this would break on the binary release?

**Comment by edulop91** [comment]
There's a chance this is a CGO issue. Would you mind running `CGO_ENABLED=0 go run main.go` and see what comes back?

**Comment by vivianho** [comment]
Bingo: 

```
ERRO[0000] Error in retrieving AWS Okta session credentials: Error retrieving credentials using aws-okta. Run `blessclient okta-setup` and then try again.: The specified item could not be found in the keyring..
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x189b36e]

goroutine 1 [running]:
github.com/chanzuckerberg/blessclient/pkg/config.(*Config).GetAWSUsername(0xc000088b60, 0x1df0520, 0xc0005ae450, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/vho/go/src/github.com/chanzuckerberg/blessclient/pkg/config/config.go:235 +0x15e
github.com/chanzuckerberg/blessclient/cmd.processRegion(0x1df0520, 0xc000372f00, 0xc000088b60, 0xc0003a6000, 0xc00008cb80, 0x9, 0xc0000c0870, 0x24, 0x0, 0x0)
	/Users/vho/go/src/github.com/chanzuckerberg/blessclient/cmd/run.go:111 +0x232
github.com/chanzuckerberg/blessclient/cmd.glob..func7(0x288ff80, 0x28b3c40, 0x0, 0x0, 0x0, 0x0)
	/Users/vho/go/src/github.com/chanzuckerberg/blessclient/cmd/run.go:93 +0x9a0
github.com/chanzuckerberg/blessclient/vendor/github.com/spf13/cobra.(*Command).execute(0x288ff80, 0x28b3c40, 0x0, 0x0, 0x288ff80, 0x28b3c40)
	/Users/vho/go/src/github.com/chanzuckerberg/blessclient/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/chanzuckerberg/blessclient/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x288f3a0, 0x0, 0x28901e0, 0xc000595f58)
	/Users/vho/go/src/github.com/chanzuckerberg/blessclient/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/chanzuckerberg/blessclient/vendor/github.com/spf13/cobra.(*Command).Execute(0x288f3a0, 0x10053b0, 0xc000080058)
	/Users/vho/go/src/github.com/chanzuckerberg/blessclient/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/chanzuckerberg/blessclient/cmd.Execute(0x1952981, 0x0)
	/Users/vho/go/src/github.com/chanzuckerberg/blessclient/cmd/root.go:53 +0x2d
main.main()
	/Users/vho/go/src/github.com/chanzuckerberg/blessclient/main.go:9 +0x22
exit status 2
```

**Comment by vivianho** [comment]
Ah, I think this error actually goes way back, I just haven't encountered it because this is the first time I am using the published releases (usually I just build it myself).

**Comment by edulop91** [comment]
I was hoping we could avoid this issue for some more time. 2 options I can think of:
- figure out how to do cross compilation and deal with cgo and all its baggage.
- attempt to push code to aws-okta and aws-vault that remove their cgo dependencies.

**Comment by edulop91** [comment]
@vivianho would you mind giving https://github.com/chanzuckerberg/blessclient/releases/tag/v0.5.0-rc0 a try? (I don't have a mac around currently)

**Comment by vivianho** [comment]
This works for me!

**Comment by edulop91** [comment]
Nice. I cross compiled it using https://github.com/karalabe/xgo. Going to have to figure out how to integrate this into the release process.

**Comment by edulop91** [comment]
@vivianho think this should be sorted out now :tada: 
Do one of the more current draft release binaries work for you?

**Comment by vivianho** [comment]
v0.4.6 works for me! I have a tiny request - can we use the upstream segmentio/aws-okta library now that cgo is supported? Would love to have yubikeys usable :)
